apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio
spec:
  replicas: 2   # run 2 pods for HA
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: sukesh632k/portfolio:latest   # 👈 replace with your DockerHub username if needed
        ports:
        - containerPort: 8080

