apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: default
  annotations:
    # Remove deprecated annotation
    # kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx   # new recommended way
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80
             - path: /port
            pathType: Prefix
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80

